"""
Example: How a 3rd party Python developer would use your model API.

They don't need scikit-learn or the model.pkl file. Just the link!
"""
import requests

# The unique URL generated by your portal
ENDPOINT = "https://model-7c993f39-3jmcbx25uq-uc.a.run.app/predict"

# The data features the model expects
test_data = {
    "bedrooms": 4,
    "sqft": 2100,
    "bathrooms": 3,
    "year_built": 2020,
    "distance_to_city_km": 2.1
}

print(f"📡 Calling Model API at: {ENDPOINT}")

try:
    response = requests.post(ENDPOINT, json=test_data)
    response.raise_for_status() # Check for errors
    
    result = response.json()
    print(f"✅ Predicted House Price: ${result['prediction']:,.2f}")
    
except Exception as e:
    print(f"❌ API call failed: {e}")
