import os
import re
import shutil
from typing import Dict

DOCKERFILE_TEMPLATE = """FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model.pkl .
COPY app.py .

EXPOSE 8080
CMD sh -c "uvicorn app:app --host 0.0.0.0 --port ${PORT:-8080}"
"""

# ── CRITICAL: versions must exactly match local venv where models were pickled ──
# numpy version mismatch causes "MT19937 is not a known BitGenerator" on startup
REQUIREMENTS_TEMPLATE = """fastapi==0.128.8
uvicorn[standard]==0.39.0
scikit-learn==1.6.1
joblib==1.5.3
numpy==2.0.2
pandas==2.3.3
pydantic==2.12.5
"""


def _safe_identifier(name: str, idx: int) -> str:
    candidate = re.sub(r"[^0-9a-zA-Z_]", "_", name.strip())
    if not candidate:
        return f"feature_{idx}"
    if candidate[0].isdigit():
        candidate = f"f_{candidate}"
    return candidate


def generate_app_wrapper(inspection: dict, model_id: str) -> str:
    feature_names = inspection.get("feature_names")
    input_count   = inspection.get("input_count")

    if feature_names:
        fields = [_safe_identifier(str(n), i) for i, n in enumerate(feature_names)]
    elif input_count:
        fields = [f"feature_{i}" for i in range(int(input_count))]
    else:
        fields = ["feature_0", "feature_1", "feature_2", "feature_3"]

    feature_fields = "\n".join(f"    {f}: float" for f in fields)
    task_type  = inspection.get("task_type", "regression")
    model_type = inspection.get("model_type", "unknown")

    if task_type == "classification":
        predict_logic = f"""
    values = [{", ".join(f"data.{f}" for f in fields)}]
    prediction = model.predict([values])[0]
    payload = {{"prediction": str(prediction)}}
    if hasattr(model, "predict_proba"):
        probs = model.predict_proba([values])[0]
        payload["probabilities"] = {{
            str(c): round(float(p), 4) for c, p in zip(model.classes_, probs)
        }}
    return payload
"""
    else:
        predict_logic = f"""
    values = [{", ".join(f"data.{f}" for f in fields)}]
    return {{"prediction": float(model.predict([values])[0])}}
"""

    return f'''import joblib
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(
    title="ML Model API",
    description="Auto-generated by ModelDeploy Platform",
    version="1.0.0",
)
app.add_middleware(
    CORSMiddleware, allow_origins=["*"],
    allow_methods=["*"], allow_headers=["*"]
)

model = joblib.load("model.pkl")


class InputData(BaseModel):
{feature_fields}


@app.get("/")
def root() -> dict:
    return {{
        "model_id": "{model_id}",
        "model": "{model_type}",
        "task": "{task_type}",
        "features": {fields},
        "status": "live",
        "docs": "/docs"
    }}


@app.post("/predict")
def predict(data: InputData) -> dict:{predict_logic}

@app.get("/health")
def health() -> dict:
    return {{"status": "ok"}}
'''


def generate_all_files(filepath: str, inspection: dict, model_id: str, output_dir: str) -> dict:
    os.makedirs(output_dir, exist_ok=True)
    shutil.copy(filepath, os.path.join(output_dir, "model.pkl"))

    dockerfile_path   = os.path.join(output_dir, "Dockerfile")
    app_path          = os.path.join(output_dir, "app.py")
    requirements_path = os.path.join(output_dir, "requirements.txt")

    with open(dockerfile_path, "w", encoding="utf-8") as f:
        f.write(DOCKERFILE_TEMPLATE)
    with open(app_path, "w", encoding="utf-8") as f:
        f.write(generate_app_wrapper(inspection, model_id))
    with open(requirements_path, "w", encoding="utf-8") as f:
        f.write(REQUIREMENTS_TEMPLATE)

    return {"dockerfile": dockerfile_path, "app_wrapper": app_path, "requirements": requirements_path}
